name: Build and Release

on:
  workflow_dispatch:
  push:
    branches: [sousou]

permissions:
  contents: write

jobs:
  release:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Fetch all tags
        run: git fetch --tags --force

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: "latest"

      - name: Cache Bun dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.bun
            node_modules
          key: ${{ runner.os }}-bun-cache-${{ hashFiles('**/bun.lockb') }}
          restore-keys: |
            ${{ runner.os }}-bun-cache-

      - name: Install deps
        run: bun install

      - name: Build
        run: bun run build

      # Release to GitHub
      - name: Release
        id: release
        run: bun run release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Release to Docker Hub
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Install jq
        run: sudo apt-get install -y jq

      - name: Extract version from package.json
        id: version
        run: echo "SOUSOU_VERSION=$(jq -r '.version' package.json)" >> $GITHUB_ENV

      - name: Build and push Docker image for sousou-admin-web
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./docker/sousou-admin-web/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/sousou-admin-web:latest
            ${{ secrets.DOCKER_USERNAME }}/sousou-admin-web:${{ env.SOUSOU_VERSION }}

      - name: Build and push Docker image for sousou-user-web
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./docker/sousou-user-web/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/sousou-user-web:latest
            ${{ secrets.DOCKER_USERNAME }}/sousou-user-web:${{ env.SOUSOU_VERSION }}
